# Generated by Django 4.1.7 on 2023-04-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_city_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(default='Серебро', max_length=50, null=True, verbose_name='Цвет/Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(default='Серебро', max_length=50, null=True, verbose_name='Цвет/Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default='Здесь скоро будит описание', null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='Здесь скоро будит описание', null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование товара'),
        ),
    ]
